version: "3.8"
services:
  backend:
    build:
      context: ./Pagina-web-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Pagina-web-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
